elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  image: logstash:latest
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  links:
    - elasticsearch
    - rabbitmq
pyrexia:
  build: pyrexia/
  ports:
    - "8080:80"
rabbitmq:
  image: rabbitmq:management
  ports:
    - "1833:1833"
    - "15672"
    - "5672"
